# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

stages:
  - stage: Build
    pool:
     name: Default
     demands: mycap
    jobs:
      - job: PrintMessage
        
        steps:
          - script: echo '****************'
          - script: echo 'starting with test'
          - script: echo '*****************'
           
      - job: Build
        

        variables:
           solution: '**/*.sln'
           buildPlatform: 'Any CPU'
           buildConfiguration: 'Release'
 
        steps:
        - task:  NuGetToolInstaller@1
        - task: NuGetCommand@2
          inputs:
            restoreSolution: '$(solution)'
        - task: VSBuild@1
          inputs:
           solution: '$(solution)'
           platform: '$(buildPlatform)'
           configuration: '$(buildConfiguration)'

        - script: echo 'Building application'
        
  - stage: Test
    jobs:
       - job: Test
         pool:
          name: Default
          demands:
          - agent.name -equals DESKTOP-TCB7QS9
        
         variables:
           solution: '**/*.sln'
           buildPlatform: 'Any CPU'
           buildConfiguration: 'Release'

         steps:
           - task: VSTest@2
             inputs:
              platform: '$(buildPlatform)'
              configuration: '$(buildConfiguration)'
           - script: echo 'Testing application'
           - task: PublishBuildArtifacts@1